# Generated by Django 5.0.14 on 2026-07-03 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_member_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS')], default='SMS', max_length=10)),
                ('event_type', models.CharField(help_text="e.g. 'payment_confirmation', 'kyc_verified'", max_length=50)),
                ('recipient', models.CharField(help_text='Phone number the message was sent to', max_length=20)),
                ('message', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
