# Generated by Django 5.0.14 on 2026-09-21 07:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_seed_welfare_accounts'),
        ('members', '0003_memberportalinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareCaseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='e.g. the constitution clause this implements.')),
                ('contribution_per_member', models.DecimalField(decimal_places=2, max_digits=18)),
                ('beneficiary_contributes', models.BooleanField(default=False, help_text='Whether the affected member is also levied for their own case.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WelfareSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_contribution', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Expected yearly welfare contribution per member.', max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Welfare settings',
            },
        ),
        migrations.CreateModel(
            name='WelfareCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('affected_person', models.CharField(blank=True, help_text="Who is sick/deceased if not the member, e.g. 'Mary W. (daughter)'.", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('contribution_per_member', models.DecimalField(decimal_places=2, max_digits=18)),
                ('beneficiary_contributes', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='PENDING_APPROVAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('levied_at', models.DateTimeField(blank=True, help_text='When the levy run over all members finished.', null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_cases', to='members.member')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='welfare.welfarecasetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WelfareContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('from_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('owed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='welfare.welfarecase')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_contribution', to='accounting.journalentry')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_contributions', to='members.member')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WelfarePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('applied_to_dues', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('to_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile money'), ('CASH', 'Cash'), ('BANK', 'Bank')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_payment', to='accounting.journalentry')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_payments', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WelfareDueSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='welfare.welfarecontribution')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='welfare.welfarepayment')),
            ],
        ),
        migrations.CreateModel(
            name='WelfarePayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile money'), ('CASH', 'Cash'), ('BANK', 'Bank')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('paid_to', models.CharField(blank=True, max_length=255)),
                ('paid_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='welfare.welfarecase')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_payout', to='accounting.journalentry')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WelfareYearClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('DONE', 'Done')], default='RUNNING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='WelfareYearSweep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_sweep', to='accounting.journalentry')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_sweeps', to='members.member')),
                ('year_close', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sweeps', to='welfare.welfareyearclose')),
            ],
        ),
        migrations.AddConstraint(
            model_name='welfarecontribution',
            constraint=models.UniqueConstraint(fields=('case', 'member'), name='welfare_one_levy_per_member'),
        ),
        migrations.AddConstraint(
            model_name='welfareyearsweep',
            constraint=models.UniqueConstraint(fields=('year_close', 'member'), name='welfare_one_sweep_per_member'),
        ),
    ]
