# Generated by Django 5.0.14 on 2026-09-21 12:18

import django.db.models.deletion
import welfare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_county_member_employer_member_marital_status_and_more'),
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfarecase',
            name='affected_family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welfare_cases', to='members.familymember'),
        ),
        migrations.AddField(
            model_name='welfarecasetype',
            name='child_max_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Children older than this aren't covered by this case type (blank = no limit).", null=True),
        ),
        migrations.AddField(
            model_name='welfarecasetype',
            name='covers',
            field=models.JSONField(default=welfare.models.default_covers, help_text='Who this case can be for: SELF and/or family relationships (SPOUSE, CHILD, PARENT, PARENT_IN_LAW, SIBLING).'),
        ),
    ]
