# Generated by Django 5.0.14 on 2026-09-27 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0007_seed_fine_accounts'),
        ('governance', '0002_meeting_papers'),
        ('members', '0007_admission_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffenceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True)),
                ('from_attendance', models.CharField(blank=True, choices=[('ABSENT', 'Absent without apology'), ('LATE', 'Late')], help_text='If set, the register can propose this fine for that mark.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('OUTSTANDING', 'Owed'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='OUTSTANDING', max_length=12)),
                ('incurred_on', models.DateField(help_text='The day the rule was broken (e.g. the meeting date).')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('charged_at', models.DateTimeField(auto_now_add=True)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('waived_reason', models.CharField(blank=True, max_length=255)),
                ('charged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='governance.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='members.member')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('waiver_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('offence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='fines.offencetype')),
            ],
            options={
                'ordering': ['incurred_on', 'charged_at'],
            },
        ),
        migrations.CreateModel(
            name='FinePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('MOBILE_MONEY', 'Mobile money')], max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('paid_on', models.DateField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fine_payments', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FineSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='fines.fine')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='fines.finepayment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['member', 'status'], name='fines_fine_member__c477d5_idx'),
        ),
    ]
