# Generated by Django 5.0.14 on 2026-07-02 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], default='en', max_length=5)),
                ('allowed_id_types', models.JSONField(default=list, help_text="e.g. ['NATIONAL_ID', 'HUDUMA'] for a Kenyan tenant")),
                ('default_loan_multiplier', models.DecimalField(decimal_places=2, default=3, max_digits=6)),
                ('wht_dividends_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('wht_interest_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('wht_rates_confirmed_by_tax_adviser', models.BooleanField(default=False)),
                ('active_sms_provider', models.CharField(default='', max_length=30)),
                ('sms_provider_backup', models.CharField(default='africastalking', max_length=30)),
                ('active_payment_provider', models.CharField(default='', max_length=30)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant configuration',
                'verbose_name_plural': 'Tenant configuration',
            },
        ),
    ]
