# Generated by Django 5.0.14 on 2026-07-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='member_number_next_sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='member_number_padding',
            field=models.PositiveSmallIntegerField(default=5, help_text='Digits to zero-pad the sequence to, e.g. 5 -> 00001'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='member_number_prefix',
            field=models.CharField(default='M-', max_length=20),
        ),
    ]
