# Generated by Django 5.0.14 on 2026-07-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_tenantconfig_member_number_next_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='member_number_suffix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='member_number_prefix',
            field=models.CharField(blank=True, default='M-', max_length=20),
        ),
    ]
