# Generated by Django 5.0.14 on 2026-07-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_tenantconfig_member_number_suffix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantconfig',
            name='active_payment_provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='active_sms_provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='sms_provider_backup',
            field=models.CharField(blank=True, default='africastalking', max_length=30),
        ),
    ]
