# Generated by Django 5.0.14 on 2026-07-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_tenantconfig_active_payment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='active_crb_provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
