# Generated by Django 5.0.14 on 2026-09-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_tenantconfig_active_crb_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='member_number_include_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='member_number_sequence_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='member_number_year_separator',
            field=models.CharField(blank=True, default='-', max_length=3),
        ),
    ]
