# Generated by Django 5.0.14 on 2026-09-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_member_number_year_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='paybill_account',
            field=models.CharField(blank=True, help_text='Account number for the paybill', max_length=40),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='paybill_name',
            field=models.CharField(blank=True, help_text='Account name shown to members', max_length=120),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='paybill_number',
            field=models.CharField(blank=True, help_text='M-Pesa paybill, e.g. 542542', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='payment_instructions',
            field=models.CharField(blank=True, help_text='One line shown under the paybill, e.g. the monthly deadline.', max_length=255),
        ),
    ]
