# Generated by Django 5.0.14 on 2026-09-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_paybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='loan_security_base',
            field=models.CharField(choices=[('DEPOSITS', 'Savings deposits'), ('SHARES', 'Share capital')], default='DEPOSITS', help_text='What the loan multiplier is applied to.', max_length=10),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='monthly_contribution_target',
            field=models.CharField(choices=[('SAVINGS', 'Mandatory monthly savings'), ('SHARES', 'Share capital')], default='SAVINGS', help_text="Where a member's monthly contribution goes.", max_length=10),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='withdrawals_enabled',
            field=models.BooleanField(default=True, help_text='Turn off while no member may take money out.'),
        ),
    ]
