# Generated by Django 5.0.14 on 2026-09-21 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0006_memberactivitysettings_member_last_warning_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_type', models.CharField(choices=[('AGM', 'Annual general meeting'), ('SGM', 'Special general meeting'), ('MONTHLY', "Monthly members' meeting"), ('COMMITTEE', 'Committee meeting'), ('BOARD', 'Board meeting')], max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('agenda', models.TextField(blank=True)),
                ('counts_for_attendance', models.BooleanField(default=True, help_text='Whether absences here count towards the inactivity rule.')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('HELD', 'Held - register closed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('notice_sent_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('APOLOGY', 'Absent with apology'), ('ABSENT', 'Absent without apology')], max_length=10)),
                ('apology_reason', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='governance.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendance', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='meetingattendance',
            constraint=models.UniqueConstraint(fields=('meeting', 'member'), name='one_attendance_per_member'),
        ),
    ]
