# Generated by Django 5.0.14 on 2026-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_meeting_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_online',
            field=models.BooleanField(default=False, help_text='An online meeting - apologies are due closer to the start.'),
        ),
    ]
