# Generated by Django 5.0.14 on 2026-07-04 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0004_loan_is_auto_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanEligibilityPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('require_kyc_verified', models.BooleanField(default=True)),
                ('require_no_active_arrears', models.BooleanField(default=True)),
                ('max_active_loans', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_membership_months', models.PositiveSmallIntegerField(default=0)),
                ('min_guarantor_coverage_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Only applies to products that require guarantors - total CONSENTED pledged amount must cover at least this ratio of amount_requested (e.g. 1.00 = 100%).', max_digits=5, null=True)),
                ('require_crb_check', models.BooleanField(default=False)),
                ('crb_deny_below_score', models.PositiveSmallIntegerField(blank=True, help_text='A CRB score below this is a hard deny.', null=True)),
                ('crb_refer_below_score', models.PositiveSmallIntegerField(blank=True, help_text='A CRB score below this (but at/above the deny threshold) is referred to manual appraisal.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_policy', to='loans.loanproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
