# Generated by Django 5.0.14 on 2026-07-03 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_member_photo'),
        ('savings', '0002_seed_default_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text='e.g. Daraja CheckoutRequestID / Selcom order id - what an inbound callback correlates against.', max_length=100)),
                ('provider_receipt', models.CharField(blank=True, help_text='e.g. M-Pesa receipt number', max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_collections', to='members.member')),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_collections', to='savings.savingsaccount')),
                ('savings_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_collection', to='savings.savingstransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
