# Generated by Django 5.0.14 on 2026-07-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('savings', '0002_seed_default_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcollection',
            name='purpose',
            field=models.CharField(choices=[('SAVINGS_DEPOSIT', 'Savings deposit'), ('SHARE_CONTRIBUTION', 'Share contribution')], default='SAVINGS_DEPOSIT', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentcollection',
            name='share_contribution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_collection', to='savings.sharecontribution'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='savings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_collections', to='savings.savingsaccount'),
        ),
    ]
