# Generated by Django 5.0.14 on 2026-09-21 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentcollection_purpose_and_more'),
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcollection',
            name='welfare_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_collection', to='welfare.welfarepayment'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='purpose',
            field=models.CharField(choices=[('SAVINGS_DEPOSIT', 'Savings deposit'), ('SHARE_CONTRIBUTION', 'Share contribution'), ('WELFARE_CONTRIBUTION', 'Welfare contribution')], default='SAVINGS_DEPOSIT', max_length=20),
        ),
    ]
