# Generated by Django 5.0.14 on 2026-09-21 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_admission_verification'),
        ('payments', '0003_paymentcollection_welfare_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcollection',
            name='registration_fee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_collection', to='members.registrationfeepayment'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='purpose',
            field=models.CharField(choices=[('SAVINGS_DEPOSIT', 'Savings deposit'), ('SHARE_CONTRIBUTION', 'Share contribution'), ('WELFARE_CONTRIBUTION', 'Welfare contribution'), ('REGISTRATION_FEE', 'Registration fee')], default='SAVINGS_DEPOSIT', max_length=20),
        ),
    ]
