# Generated by Django 5.0.14 on 2026-09-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0001_initial'),
        ('payments', '0004_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcollection',
            name='fine_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_collection', to='fines.finepayment'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='purpose',
            field=models.CharField(choices=[('SAVINGS_DEPOSIT', 'Savings deposit'), ('SHARE_CONTRIBUTION', 'Share contribution'), ('WELFARE_CONTRIBUTION', 'Welfare contribution'), ('REGISTRATION_FEE', 'Registration fee'), ('FINE_PAYMENT', 'Fine payment')], default='SAVINGS_DEPOSIT', max_length=20),
        ),
    ]
