# Generated by Django 5.0.14 on 2026-09-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_fines_and_partial_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcollection',
            name='for_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
