# Generated by Django 5.0.14 on 2026-07-02 18:01

import django.db.models.deletion
import members.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_number', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('ORDINARY', 'Ordinary'), ('ASSOCIATE', 'Associate'), ('JUNIOR', 'Junior'), ('CORPORATE', 'Corporate')], default='ORDINARY', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('EXITED', 'Exited')], default='ACTIVE', max_length=20)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('other_names', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], max_length=10)),
                ('id_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('HUDUMA', 'Huduma Namba'), ('NIDA', 'NIDA (Tanzania)'), ('PASSPORT', 'Passport')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.TextField(blank=True)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kyc_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Linked once this member has (or is given) self-service login access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('id_type', 'id_number')},
            },
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_DOCUMENT', 'ID document'), ('PASSPORT_PHOTO', 'Passport photo'), ('PROOF_OF_ADDRESS', 'Proof of address'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=members.models.member_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('NEXT_OF_KIN', 'Next of kin'), ('NOMINEE', 'Nominee'), ('BENEFICIARY', 'Beneficiary')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(help_text='e.g. spouse, child, parent, sibling', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('benefit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='GuarantorConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONSENTED', 'Consented'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='members.member')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guaranteeing_for', to='members.member')),
            ],
            options={
                'unique_together': {('guarantor', 'borrower')},
            },
        ),
    ]
