# Generated by Django 5.0.14 on 2026-09-21 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_memberportalinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='county',
            field=models.CharField(blank=True, help_text='County / region of residence.', max_length=80),
        ),
        migrations.AddField(
            model_name='member',
            name='employer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced / separated')], max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_status',
            field=models.CharField(choices=[('DRAFT', 'Not yet submitted'), ('PENDING', 'Awaiting approval'), ('APPROVED', 'Approved')], default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='id_number_match',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='ocr_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='document_type',
            field=models.CharField(choices=[('ID_DOCUMENT', 'ID document'), ('ID_FRONT', 'ID card - front'), ('ID_BACK', 'ID card - back'), ('BIRTH_CERT', 'Birth certificate'), ('MARRIAGE_CERT', 'Marriage certificate'), ('PASSPORT_PHOTO', 'Passport photo'), ('PROOF_OF_ADDRESS', 'Proof of address'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('PARENT_IN_LAW', 'Parent-in-law'), ('SIBLING', 'Sibling')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], max_length=10)),
                ('id_number', models.CharField(blank=True, help_text='National ID / NIDA, if they have one.', max_length=50)),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_next_of_kin', models.BooleanField(default=False)),
                ('is_deceased', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REMOVED', 'Removed')], default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='members.member')),
            ],
            options={
                'ordering': ['relationship', 'date_of_birth', 'full_name'],
            },
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='members.familymember'),
        ),
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('PROFILE', 'Personal details'), ('FAMILY_ADD', 'Add family member'), ('FAMILY_UPDATE', 'Change family member'), ('FAMILY_REMOVE', 'Remove family member')], max_length=20)),
                ('changes', models.JSONField(default=dict)),
                ('before', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True, help_text="The member's explanation, e.g. a name change after marriage.")),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='members.familymember')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='members.member')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
