# Generated by Django 5.0.14 on 2026-09-21 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_approve_already_verified_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberActivitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_rule_enabled', models.BooleanField(default=True)),
                ('warn_after_months', models.PositiveSmallIntegerField(default=2)),
                ('inactive_after_months', models.PositiveSmallIntegerField(default=3)),
                ('min_monthly_contribution', models.DecimalField(decimal_places=2, default=0, help_text='A month only counts as contributed if mandatory savings deposits reach this (0 = any amount).', max_digits=18)),
                ('meeting_rule_enabled', models.BooleanField(default=True)),
                ('warn_after_meetings', models.PositiveSmallIntegerField(default=2)),
                ('inactive_after_meetings', models.PositiveSmallIntegerField(default=3)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Member activity settings',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='last_warning_key',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='InactivityFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('CONTRIBUTIONS', 'Missed monthly contributions'), ('MEETINGS', 'Missed meetings without apology')], max_length=15)),
                ('detail', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting decision'), ('CONFIRMED', 'Archived'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_flags', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('EXITED', 'Exited')], max_length=20)),
                ('to_status', models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('EXITED', 'Exited')], max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='members.member')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
