# Generated by Django 5.0.14 on 2026-09-21 13:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_seed_registration_fee_account'),
        ('members', '0006_memberactivitysettings_member_last_warning_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, help_text='One-off, non-refundable fee; SACCO income. 0 = no fee required.', max_digits=18)),
                ('verification_months', models.PositiveSmallIntegerField(default=3, help_text='Consecutive months of mandatory monthly contributions needed to be verified.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Membership settings',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='verified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('other_names', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], max_length=10)),
                ('id_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('HUDUMA', 'Huduma Namba'), ('NIDA', 'NIDA (Tanzania)'), ('PASSPORT', 'Passport')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.TextField(blank=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced / separated')], max_length=10)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('county', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('fee_collected', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fee_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('MOBILE_MONEY', 'Mobile money')], max_length=15)),
                ('fee_reference', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application', to='members.member')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationFeePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('MOBILE_MONEY', 'Mobile money')], max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('paid_on', models.DateField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_fees', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
