# Generated by Django 5.0.14 on 2026-09-27 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_admission_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_type',
            field=models.CharField(blank=True, choices=[('NATIONAL_ID', 'National ID'), ('HUDUMA', 'Huduma Namba'), ('NIDA', 'NIDA (Tanzania)'), ('PASSPORT', 'Passport')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('id_number', ''), _negated=True), fields=('id_type', 'id_number'), name='unique_id_number_when_known'),
        ),
    ]
