# Generated by Django 5.0.14 on 2026-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_fines_and_partial_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberactivitysettings',
            name='monthly_due_day',
            field=models.PositiveSmallIntegerField(default=18, help_text='Day of the month the monthly contribution is due (e.g. 18).'),
        ),
    ]
