# Generated by Django 5.0.14 on 2026-09-28 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_seed_exit_accounts'),
        ('members', '0009_contribution_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inactivity_grace_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='suspended_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='membershipsettings',
            name='exit_deducts_debts',
            field=models.BooleanField(default=True, help_text='Take unpaid fines and welfare dues out of the refund.'),
        ),
        migrations.AddField(
            model_name='membershipsettings',
            name='exit_refund_percent',
            field=models.DecimalField(decimal_places=2, default=100, help_text="Percentage of a resigning member's savings refunded (e.g. 90).", max_digits=5),
        ),
        migrations.AddField(
            model_name='membershipsettings',
            name='notice_months',
            field=models.PositiveSmallIntegerField(default=3, help_text='Months of notice a resigning member must give.'),
        ),
        migrations.AddField(
            model_name='membershipsettings',
            name='probation_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Days from registration before a member can be full (e.g. 90).'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('SUSPENDED', 'Suspended'), ('NOTICE', 'Serving notice'), ('EXITED', 'Exited')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberstatuschange',
            name='from_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('SUSPENDED', 'Suspended'), ('NOTICE', 'Serving notice'), ('EXITED', 'Exited')], max_length=20),
        ),
        migrations.AlterField(
            model_name='memberstatuschange',
            name='to_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('SUSPENDED', 'Suspended'), ('NOTICE', 'Serving notice'), ('EXITED', 'Exited')], max_length=20),
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOTICE', 'Notice given'), ('APPROVED', 'Approved - serving notice'), ('PAID', 'Refunded and closed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='NOTICE', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('notice_given_on', models.DateField()),
                ('leaving_on', models.DateField(help_text='When the notice period ends and a refund may be paid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('savings_at_exit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('refund_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('debts_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('refund_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('retained_by_group', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resignations', to='members.member')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
