# Generated by Django 5.0.14 on 2026-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_resignation_and_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberactivitysettings',
            name='apology_days_before_physical',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberactivitysettings',
            name='apology_hours_before_online',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
