# Generated by Django 5.0.14 on 2026-07-05 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_seed_distribution_accounts'),
        ('members', '0003_memberportalinvite'),
        ('savings', '0002_seed_default_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basis_balance', models.DecimalField(decimal_places=2, help_text="Member's share-capital or savings-account balance as of period_end that the rate was applied to.", max_digits=18)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('POSTED', 'Posted'), ('PAID', 'Paid')], default='PROPOSED', max_length=20)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_entry', to='accounting.journalentry')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_entries', to='members.member')),
                ('savings_account', models.ForeignKey(blank=True, help_text='Set for INTEREST entries - the specific SavingsAccount the balance was computed against.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_entries', to='savings.savingsaccount')),
            ],
            options={
                'ordering': ['run', 'member'],
            },
        ),
        migrations.CreateModel(
            name='DistributionPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='distributions.distributionentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('DIVIDEND', 'Dividend (on share capital)'), ('INTEREST', 'Interest/rebate (on savings deposits)')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(help_text="MVP simplification: the declared rate is applied directly to each member's/account's balance AS OF this date - no average-daily-balance calculation, no prorating by period length. Flagged here the same way WHT rates are flagged for a tax adviser to confirm.")),
                ('rate', models.DecimalField(decimal_places=4, help_text="e.g. 0.0500 = 5%. Snapshotted at proposal time (board-declared for dividends, defaults to the product's own interest_rate for interest runs) so a later rate change never reprices an already-proposed/approved run.", max_digits=6)),
                ('wht_rate', models.DecimalField(decimal_places=4, default=0, help_text='Snapshotted from TenantConfig.wht_dividends_rate / wht_interest_rate at proposal time - never re-read at approval time.', max_digits=5)),
                ('wht_rates_confirmed_by_tax_adviser', models.BooleanField(default=False, help_text='Snapshot of TenantConfig.wht_rates_confirmed_by_tax_adviser at proposal time - flags this specific run for tax-adviser review, same posture as the config field.')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved - posted to ledger'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('savings_product', models.ForeignKey(blank=True, help_text="Required for an INTEREST run (rate applies to this product's accounts). Always null for DIVIDEND.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_runs', to='savings.savingsproduct')),
            ],
            options={
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.AddField(
            model_name='distributionentry',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='distributions.distributionrun'),
        ),
        migrations.AlterUniqueTogether(
            name='distributionentry',
            unique_together={('run', 'member')},
        ),
    ]
