# Generated by Django 5.0.14 on 2026-07-03 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_seed_chart_of_accounts'),
        ('members', '0002_member_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('product_type', models.CharField(choices=[('MANDATORY_MONTHLY', 'Mandatory monthly'), ('VOLUNTARY', 'Voluntary'), ('FIXED_TERM', 'Fixed/term'), ('GOAL', 'Goal'), ('JUNIOR', 'Junior')], max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=0, help_text='Annual rate, e.g. 0.0500 = 5%', max_digits=6)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('opened_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_accounts', to='members.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='savings.savingsproduct')),
            ],
            options={
                'unique_together': {('member', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='savings_transaction', to='accounting.journalentry')),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='savings.savingsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ShareAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='share_account', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='ShareContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='share_contribution', to='accounting.journalentry')),
                ('share_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='savings.shareaccount')),
            ],
        ),
    ]
