# Generated by Django 5.0.14 on 2026-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_seed_default_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingstransaction',
            name='for_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
