# Generated by Django 5.0.14 on 2026-09-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_contribution_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharecontribution',
            name='for_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
