# Generated by Django 5.0.14 on 2026-07-03 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_memberportalinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('interest_method', models.CharField(choices=[('REDUCING_BALANCE', 'Reducing balance'), ('FLAT', 'Flat')], max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Annual rate, e.g. 0.1200 = 12%', max_digits=6)),
                ('min_term_months', models.PositiveSmallIntegerField(default=1)),
                ('max_term_months', models.PositiveSmallIntegerField(default=12)),
                ('max_multiple_of_deposits', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('requires_guarantors', models.BooleanField(default=True)),
                ('min_guarantors', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=18)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('interest_method', models.CharField(choices=[('REDUCING_BALANCE', 'Reducing balance'), ('FLAT', 'Flat')], max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('status', models.CharField(choices=[('PENDING_GUARANTORS', 'Awaiting guarantors'), ('PENDING_APPRAISAL', 'Pending appraisal'), ('APPRAISED', 'Appraised - awaiting decision'), ('APPROVED', 'Approved - awaiting disbursement'), ('REJECTED', 'Rejected')], default='PENDING_GUARANTORS', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('appraised_at', models.DateTimeField(blank=True, null=True)),
                ('appraisal_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appraised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='members.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pledged_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONSENTED', 'Consented'), ('DECLINED', 'Declined'), ('RELEASED', 'Released')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_guarantees', to='members.member')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loan')),
            ],
            options={
                'unique_together': {('loan', 'guarantor')},
            },
        ),
    ]
