# Generated by Django 5.0.14 on 2026-07-03 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_seed_loan_accounts'),
        ('loans', '0002_seed_default_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='default_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='defaulted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_method',
            field=models.CharField(blank=True, choices=[('SAVINGS_CREDIT', 'Credited to savings account'), ('MOBILE_MONEY', 'Mobile money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING_GUARANTORS', 'Awaiting guarantors'), ('PENDING_APPRAISAL', 'Pending appraisal'), ('APPRAISED', 'Appraised - awaiting decision'), ('APPROVED', 'Approved - awaiting disbursement'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursement pending confirmation'), ('ACTIVE', 'Active - being repaid'), ('CLOSED', 'Closed - fully repaid'), ('DEFAULTED', 'Defaulted')], default='PENDING_GUARANTORS', max_length=20),
        ),
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='loans.loan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayment', to='accounting.journalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loan')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='loans.loan')),
            ],
            options={
                'ordering': ['loan', 'installment_number'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
    ]
