# Generated by Django 5.0.14 on 2026-07-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_closed_at_loan_default_notes_loan_defaulted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_auto_decision',
            field=models.BooleanField(default=False),
        ),
    ]
