# Generated by Django 5.0.14 on 2026-10-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_is_auto_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_period',
            field=models.CharField(choices=[('PER_MONTH', 'Per month (p.m.)'), ('PER_YEAR', 'Per year (p.a.)')], default='PER_YEAR', max_length=10),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='interest_period',
            field=models.CharField(choices=[('PER_MONTH', 'Per month (p.m.)'), ('PER_YEAR', 'Per year (p.a.)')], default='PER_YEAR', help_text='Whether the rate is per month (p.m.) or per year (p.a.).', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, help_text='Rate as quoted, e.g. 0.1000 = 10% (see interest_period)', max_digits=6),
        ),
    ]
