# Generated by Django 5.0.14 on 2026-07-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0003_seed_default_permissions_and_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
