# Generated by Django 5.0.14 on 2026-09-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0015_secretary_role_profile_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='role',
            name='assistant_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='accesscontrol.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='max_holders',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many people may hold this at once (blank = no limit).', null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
