# Generated by Django 5.0.14 on 2026-09-21 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.CharField(blank=True, help_text='Name and phone at the time.', max_length=200)),
                ('action', models.CharField(choices=[('LOGIN', 'Signed in'), ('LOGIN_FAILED', 'Failed sign-in'), ('VIEW', 'Viewed'), ('CREATE', 'Created / submitted'), ('UPDATE', 'Changed'), ('DELETE', 'Deleted'), ('EVENT', 'Security event')], db_index=True, max_length=15)),
                ('event', models.CharField(blank=True, db_index=True, help_text='e.g. password.reset', max_length=60)),
                ('area', models.CharField(blank=True, db_index=True, help_text='e.g. members, loans', max_length=40)),
                ('summary', models.CharField(max_length=300)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=60)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['user', '-at'], name='audit_audit_user_id_8af46e_idx')],
            },
        ),
    ]
