from django.urls import path

from . import activity_views, admission_views, profile_views, views

app_name = "members"

urlpatterns = [
    path("", views.MemberListCreateView.as_view(), name="member_list_create"),
    path("me/", views.MyMemberView.as_view(), name="my_member"),
    path("me/verification/", admission_views.MyVerificationView.as_view(), name="my_verification"),
    path("applications/", admission_views.ApplicationListCreateView.as_view(), name="application_list"),
    path("applications/<uuid:pk>/", admission_views.ApplicationDetailView.as_view(), name="application_detail"),
    path("applications/<uuid:pk>/approve/", admission_views.ApplicationDecisionView.as_view(approve=True),
         name="application_approve"),
    path("applications/<uuid:pk>/reject/", admission_views.ApplicationDecisionView.as_view(approve=False),
         name="application_reject"),
    path("applications/<uuid:pk>/cancel/", admission_views.ApplicationCancelView.as_view(), name="application_cancel"),
    path("membership-settings/", admission_views.MembershipSettingsView.as_view(), name="membership_settings"),
    path("me/photo/", views.MyMemberPhotoUploadView.as_view(), name="my_member_photo_upload"),
    path("me/profile/", profile_views.MyProfileView.as_view(), name="my_profile"),
    path("me/activity/", activity_views.MyActivityView.as_view(), name="my_activity"),
    path("activity/settings/", activity_views.ActivitySettingsView.as_view(), name="activity_settings"),
    path("activity/run/", activity_views.RunActivityCheckView.as_view(), name="activity_run"),
    path("activity/flags/", activity_views.FlagListView.as_view(), name="activity_flags"),
    path("activity/flags/<uuid:pk>/confirm/", activity_views.FlagDecisionView.as_view(confirm=True), name="flag_confirm"),
    path("activity/flags/<uuid:pk>/dismiss/", activity_views.FlagDecisionView.as_view(confirm=False), name="flag_dismiss"),
    path("activity/dormant/", activity_views.DormantMembersView.as_view(), name="activity_dormant"),
    path("me/profile/changes/", profile_views.MyProfileChangeView.as_view(), name="my_profile_changes"),
    path("me/family/", profile_views.MyFamilyView.as_view(), name="my_family"),
    path("me/family/<uuid:pk>/", profile_views.MyFamilyDetailView.as_view(), name="my_family_detail"),
    path("me/documents/", profile_views.MyDocumentUploadView.as_view(), name="my_documents"),
    path(
        "me/change-requests/<uuid:pk>/cancel/",
        profile_views.MyChangeRequestCancelView.as_view(),
        name="my_change_request_cancel",
    ),
    path("change-requests/", profile_views.ChangeRequestListView.as_view(), name="change_request_list"),
    path(
        "change-requests/<uuid:pk>/approve/",
        profile_views.ChangeRequestDecisionView.as_view(approve=True),
        name="change_request_approve",
    ),
    path(
        "change-requests/<uuid:pk>/reject/",
        profile_views.ChangeRequestDecisionView.as_view(approve=False),
        name="change_request_reject",
    ),
    path("portal-invites/", views.PortalInviteListView.as_view(), name="portal_invite_list"),
    path(
        "portal-invites/<uuid:pk>/revoke/",
        views.PortalInviteRevokeView.as_view(),
        name="portal_invite_revoke",
    ),
    path(
        "portal-invites/<str:token>/accept/",
        views.PortalInviteAcceptView.as_view(),
        name="portal_invite_accept",
    ),
    path("<uuid:pk>/", views.MemberDetailView.as_view(), name="member_detail"),
    path("<uuid:pk>/verification/", admission_views.MemberVerificationView.as_view(), name="member_verification"),
    path("<uuid:pk>/registration-fee/", admission_views.RegistrationFeeView.as_view(), name="member_registration_fee"),
    path("<uuid:pk>/verify-kyc/", views.MemberKycVerifyView.as_view(), name="member_kyc_verify"),
    path("<uuid:pk>/family/", profile_views.MemberFamilyView.as_view(), name="member_family"),
    path("<uuid:pk>/reactivate/", activity_views.ReactivateMemberView.as_view(), name="member_reactivate"),
    path("<uuid:pk>/documents/", profile_views.MemberDocumentListView.as_view(), name="member_documents"),
    path("<uuid:pk>/photo/", views.MemberPhotoUploadView.as_view(), name="member_photo_upload"),
    path("<uuid:member_id>/portal-invite/", views.InvitePortalAccessView.as_view(), name="invite_portal_access"),
    path("guarantor-consents/", views.GuarantorConsentListCreateView.as_view(), name="guarantor_consent_list_create"),
    path("guarantor-consents/<uuid:pk>/respond/", views.GuarantorConsentRespondView.as_view(), name="guarantor_consent_respond"),
]
